Repository wecode-bootcamp-korea/14-1st-OurPlays-frontend, pull requests merged in 2020-11, with the labels that each got.

#1 [박영준] feature/Login 멘토님 리뷰 반영
  .vscode/launch.json
  public/images/youngjoonpark/Honeybadger.png
  public/images/youngjoonpark/arrow-img.png
  public/images/youngjoonpark/blog-icon.png
  public/images/youngjoonpark/brunch icon.png
  public/images/youngjoonpark/camera-icon.svg
  public/images/youngjoonpark/category-img/그 외 장소.png
  public/images/youngjoonpark/category-img/빌라.png
  public/images/youngjoonpark/category-img/사무실.png
  public/images/youngjoonpark/category-img/스튜디오.png
  public/images/youngjoonpark/category-img/아파트.png
  public/images/youngjoonpark/category-img/옥상.png
  public/images/youngjoonpark/category-img/원룸.png
  public/images/youngjoonpark/category-img/주택.png
  public/images/youngjoonpark/category-img/카페식당.png
  public/images/youngjoonpark/category-img/팬션.png
  public/images/youngjoonpark/facebook-icon.png
  public/images/youngjoonpark/hourplace-logo.svg
  public/images/youngjoonpark/insta-icon.png
  public/images/youngjoonpark/munch factory.png
  public/images/youngjoonpark/search-icon.png
  public/index.html
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.scss
  src/Pages/Login/Login.jsx
  src/Pages/Login/Login.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#4 [김동하] feature/Main UI 및 기능 구현
  package-lock.json
  package.json
  public/Data/Data.json
  public/Data/PlaceData.json
  public/images/donghakim/Main/avatar1.jpg
  public/images/donghakim/Main/avatar2.jpg
  public/images/donghakim/Main/avatar3.jpg
  public/images/donghakim/Main/avatar4.jpg
  public/images/donghakim/Main/avatar5.jpg
  public/images/donghakim/honeybadger icon2.jpg
  src/.eslintrc.json
  src/Components/Category/Category.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Nav/Nav.jsx
  src/Components/Nav/Nav.scss
  src/Components/Slide/Slide.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Main/Main.jsx
  src/Pages/Main/Main.scss
  src/Pages/Main/components/ChatBoard.jsx
  src/Pages/Main/components/Chatbot.jsx
  src/Pages/Main/components/Chatbot.scss
  src/Pages/Main/components/LandingPage.jsx
  src/Pages/Main/components/LandingPage.scss
  src/Pages/Main/components/Slider.jsx
  src/Pages/Main/components/Sliders.jsx
  src/Pages/Main/components/Sliders.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: Accepted, Status: 리뷰 요청

#5 [박영준] feature/Footer UI완성 및 기능구현
  public/images/youngjoonpark/brunch-icon.png
  public/images/youngjoonpark/munch-factory.png
  src/Components/Footer/Components/FooterIcons.jsx
  src/Components/Footer/Components/FooterInfos.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#9 [박영준] fix/Login 로그인페이지 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/.eslintrc.json
  src/Components/Nav/Nav.scss
  src/Pages/Login/Login.jsx
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.jsx
  src/Pages/Main/components/Chatbot.jsx
Labels: Status: 리뷰 요청

#11 [14기 김동하] fixed - 대소문자 오류 해결
  src/Pages/Main/components/ChatBot.jsx
  src/Pages/Main/components/ChatBot.scss
Labels: Status: 리뷰 요청

#8 [김동하] feature/ProductDetail UI 및 기능 추가
  .gitignore
  package-lock.json
  package.json
  public/Data/PlaceData.json
  public/images/donghakim/another.png
  public/images/donghakim/img1.jpeg
  public/images/donghakim/img2.jpeg
  public/images/donghakim/img3.jpeg
  public/images/donghakim/img4.jpeg
  public/images/donghakim/map.png
  public/images/youngjoonpark/bomb.jpg
  src/Components/Category/Category.jsx
  src/Components/Footer/Footer.jsx
  src/Components/Loading/Loading.jsx
  src/Components/Nav/Nav.jsx
  src/Pages/BookMark/BookMarkList.jsx
  src/Pages/BookMark/BookMarkList.scss
  src/Pages/BookMark/components/BookMarkLists.jsx
  src/Pages/BookMark/components/BookMarkLists.scss
  src/Pages/BookMark/components/Room.jsx
  src/Pages/BookMark/components/Room.scss
  src/Pages/Login/Login.jsx
  src/Pages/Main/Main.jsx
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/components/Calendar.jsx
  src/Pages/ProductDetail/components/Calendar.scss
  src/Pages/ProductDetail/components/DetailSlider.jsx
  src/Pages/ProductDetail/components/DetailSlider.scss
  src/Pages/ProductDetail/components/MapContainer.jsx
  src/Pages/ProductDetail/components/MapContainer.scss
  src/Pages/ProductDetail/components/MapElement.jsx
  src/Pages/ProductDetail/components/MapElement.scss
  src/Pages/ProductDetail/components/Modal.jsx
  src/Pages/ProductDetail/components/Modal.scss
  src/Pages/ProductDetail/components/Pagination.jsx
  src/Pages/ProductDetail/components/ReviewElement.jsx
  src/Pages/ProductDetail/components/ReviewElement.scss
  src/Pages/ProductDetail/components/ReviewList.jsx
  src/Pages/ProductDetail/components/ReviewList.scss
  src/Pages/ProductDetail/components/SelectDropdown.jsx
  src/Pages/ProductDetail/components/SelectDropdown.scss
  src/Pages/ProductDetail/components/Star.jsx
  src/Pages/ProductDetail/components/TagLists.jsx
  src/Pages/ProductDetail/components/TagLists.scss
  src/Pages/Reservation/Reservation.jsx
  src/Pages/Reservation/Reservation.scss
  src/Pages/Reservation/component/Reservated.jsx
  src/Pages/UploadImage/UploadImage.jsx
  src/Pages/UploadImage/UploadImage.scss
  src/Routes.js
  src/config.js
Labels: Status: Accepted, Status: 리뷰 요청

#14 [14기 박영준] fix/Footer conflict 해결
  package-lock.json
  prettierrc.json
  src/Pages/Main/Main.jsx
  src/Pages/Main/components/ChatBoard.jsx
  src/Pages/Main/components/ChatBot.jsx
  src/Pages/Main/components/LandingPage.jsx
  src/Pages/Main/components/Slider.jsx
  src/config.js
Labels: Status: 리뷰 요청, 리뷰 진행 중

#7 [박영준] feature/ProductList UI완성 기능구현 중
  package.json
  public/Data/PlaceData.json
  public/images/youngjoonpark/bookmark-empty.png
  public/images/youngjoonpark/bookmark-filled.png
  public/images/youngjoonpark/control-bar.png
  public/images/youngjoonpark/star-icon.svg
  public/images/youngjoonpark/옥상.jpg
  src/Components/Category/Category.scss
  src/Components/Nav/Components/NavIcons.jsx
  src/Components/Nav/Nav.jsx
  src/Pages/Login/Login.jsx
  src/Pages/Main/components/ChatBot.jsx
  src/Pages/Main/components/Sliders.jsx
  src/Pages/ProductList/Components/Bookmark.jsx
  src/Pages/ProductList/Components/Buttons.jsx
  src/Pages/ProductList/Components/Buttons.scss
  src/Pages/ProductList/Components/ControlButtons.jsx
  src/Pages/ProductList/Components/ModalCount.jsx
  src/Pages/ProductList/Components/ModalCount.scss
  src/Pages/ProductList/Components/ModalPrice.jsx
  src/Pages/ProductList/Components/ModalPrice.scss
  src/Pages/ProductList/Components/ProductLists.jsx
  src/Pages/ProductList/Components/RoomList.jsx
  src/Pages/ProductList/Components/RoomListGrade.jsx
  src/Pages/ProductList/ProductList.jsx
  src/Pages/ProductList/ProductList.scss
Labels: Status: 리뷰 요청

#10 [14기 박영준] fix/Nav 기능 구현
  src/Components/Nav/Nav.jsx
  src/Components/Nav/Nav.scss
  src/Pages/Login/Login.jsx
  src/Pages/Main/components/LandingPage.jsx
  src/Pages/Main/components/Sliders.jsx
  src/Pages/SignUp/SignUp.jsx
Labels: Status: 리뷰 요청

#16 [14기 김동하] Product Detail 멘토님 리뷰 반영했습니다.
  src/Components/Footer/Components/FooterIcons.jsx
  src/Components/Nav/Nav.jsx
  src/Pages/BookMark/BookMarkList.jsx
  src/Pages/BookMark/components/BookMarkLists.jsx
  src/Pages/BookMark/components/Room.jsx
  src/Pages/Main/Main.jsx
  src/Pages/Main/components/ChatBot.jsx
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductDetail/components/Modal.jsx
  src/Pages/Reservation/component/Reservated.jsx
  src/Pages/UploadImage/UploadImage.jsx
  src/config.js
Labels: Status: Accepted, Status: 리뷰 요청

#19 [14기 박영준] Fix signup 페이지 하단 padding 수정
  src/Pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#20 [14기 김동하] nav css 수정했습니다.
  package-lock.json
  package.json
  src/Components/Category/Components/CategoryItems.jsx
  src/Components/Loading/Loading.jsx
  src/Components/Loading/Loading.scss
  src/Components/Loading/Loding.scss
  src/Components/Loading/loading.gif
  src/Components/Loading/loading2.gif
  src/Components/Nav/Nav.scss
  src/Pages/BookMark/components/BookMarkLists.scss
  src/Pages/BookMark/components/Room.jsx
  src/Pages/BookMark/components/Room.scss
  src/Pages/Login/Login.jsx
  src/Pages/Login/Login.scss
  src/Pages/Main/components/ChatBot.jsx
  src/Pages/Main/components/ChatBot.scss
  src/Pages/Main/components/LandingPage.scss
  src/Pages/Main/components/Slider.jsx
  src/Pages/Main/components/Sliders.jsx
  src/Pages/Main/components/Sliders.scss
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductDetail/components/MapContainer.jsx
  src/Pages/ProductDetail/components/MapElement.jsx
  src/Pages/ProductDetail/components/ReviewList.jsx
  src/Pages/Reservation/Reservation.jsx
  src/Pages/Reservation/component/Reservated.jsx
  src/config.js
Labels: Status: 리뷰 요청

#22 [14기 박영준] Fix/login 최종수정
  src/Pages/Login/Login.jsx
  src/config.js
Labels: Status: 리뷰 요청

#21 [14기 박영준] signup css 수정했습니다!
  src/Components/Category/Category.jsx
  src/Components/Category/Category.scss
  src/Components/Category/Components/CategoryItems.jsx
  src/Pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#23 [14기 박영준] modify/ProductList 동적라우팅 적용
  src/Pages/ProductDetail/ProductDetail.jsx
  src/Pages/ProductList/Components/ProductLists.jsx
  src/Pages/ProductList/Components/RoomList.jsx
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#24 [14기 김동하] 마지막 pr입니다.
  src/Pages/Main/Main.jsx
  src/Pages/Main/Main.scss
  src/Pages/Main/components/LandingPage.jsx
  src/Pages/SignUp/components/Auth.jsx
  src/Pages/SignUp/components/Auth.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#25 [14기 박영준] category 최종수정
  src/Components/Category/Category.jsx
  src/Components/Category/Category.scss
  src/Components/Category/Components/CategoryItems.jsx
  src/Pages/Main/components/Sliders.jsx
  src/Pages/ProductList/Components/ProductLists.jsx
  src/Routes.js
  src/config.js
Labels: Status: Accepted
